name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/crowdfunding-app:latest
          ${{ secrets.DOCKER_USERNAME }}/crowdfunding-app:${{ github.sha }}

    - name: Verify deployment
      run: |
        echo "✅ Docker image pushed to Docker Hub!"
        echo "📦 Image: ${{ secrets.DOCKER_USERNAME }}/crowdfunding-app:latest"