name: CD Debug

on:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
    - name: Check secrets exist
      run: |
        echo "Checking if Docker secrets are available..."
        if [ -n "$DOCKER_USERNAME" ]; then
          echo "✅ DOCKER_USERNAME is SET"
        else
          echo "❌ DOCKER_USERNAME is EMPTY"
        fi
        
        if [ -n "$DOCKER_PASSWORD" ]; then
          echo "✅ DOCKER_PASSWORD is SET"
        else
          echo "❌ DOCKER_PASSWORD is EMPTY"
        fi
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Simple Docker build test
      run: |
        docker build -t local-test .
        echo "✅ Local build successful"