name: CD Debug

on:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check secrets exist
      run: |
        echo "Checking if Docker secrets are available..."
        if [ -n "$DOCKER_USERNAME" ]; then
          echo "✅ DOCKER_USERNAME is SET (length: ${#DOCKER_USERNAME})"
        else
          echo "❌ DOCKER_USERNAME is EMPTY"
        fi
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        ls -la  # Покажет файлы в рабочей директории
        docker build -t local-test .
        echo "✅ Local build successful"